services:
  postgres-newsletter:
    image: postgres
    container_name: postgres-newsletter
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha123
    ports:
      - "5434:5432"
volumes:
  postgres-data: