server:
  port: 8083

spring:
  application:
    name: newsletter-api

  cloud:
    openfeign:
      client:
        config:
          empresaClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC

  sql:
    init:
      continue-on-error: true
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jefferplay.silva@gmail.com
    password: zald yikd doei rucd
    properties:
      mail:
        smtp:
#          auth: true
          starttls:
            enable: true
eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka/
url:
  empresa.host: http://localhost:8082/v1.0/empresas